version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql_scla
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: SCLA
    ports:
      - "3306:3306"
    networks:
      - scla-network

networks:
  scla-network:
    external: true
